export const SOCIAL_MODES = {
  FOLLOW: "FOLLOW",
  SHARE: "SHARE"
}

export const SOCIAL_TYPES = {
  FACEBOOK: "FACEBOOK",
  INSTAGRAM: "INSTAGRAM",
  LINKEDIN: "LINKEDIN",
  TWITTER: "TWITTER",
  CUSTOM: "CUSTOM",
  EMAIL: "EMAIL",
  PINTEREST: "PINTEREST",
  WHATSAPP: "WHATSAPP",
}

export const SOCIAL_ICON_SHAPES = {
  ROUNDED: 'ROUNDED',
}

export const LINK_TYPES = {
  EXTERNAL: "EXTERNAL",
  INTERNAL: "INTERNAL",
}